#!/usr/bin/env python3
"""Scaffold a production-grade local FastAPI project around a Hugging Face model.

Generates a layered app (main.py + core/config.py + core/model.py + api/routes.py +
schemas.py), tests, requirements.txt, .env.example, README.md and .gitignore. The
task-specific pieces (model.py, schemas.py, the inference endpoint) differ per task
family; everything else (lifespan loading, health probes, CORS, warm-up, error
handling) is shared.

This script only writes files — it does not install dependencies or start the server.

Usage:
    python scaffold_project.py --model-id <id> --task <task-family> --output-dir <dir>

Task families: text-classification | token-classification | embeddings | image-generation
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from string import Template

TASK_CHOICES = (
    "text-classification",
    "token-classification",
    "embeddings",
    "image-generation",
)


def slugify(model_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "-", model_id).strip("-").lower()


# ---------------------------------------------------------------------------
# Shared files (identical structure across all task families)
# ---------------------------------------------------------------------------

MAIN_PY = Template('''\
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.core.config import get_settings
from app.core.model import load_model, warm_up
from app.api.routes import router


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    app.state.model_bundle = load_model(settings)   # loaded once, never per-request
    warm_up(app.state.model_bundle)                  # pays the first-call cost at startup
    app.state.model_ready = True
    yield
    app.state.model_bundle = None
    app.state.model_ready = False


# NOTE: this service has NO authentication and NO rate limiting. It is intended for
# local, single-user use only (see README). Do not expose it beyond localhost without
# adding auth, rate limiting, and a hardened CORS policy first.
app = FastAPI(title=$title, lifespan=lifespan)

# Reject oversized request bodies early. A single huge payload is a memory-DoS vector
# even with per-field caps, because the body is read and JSON-parsed before field
# validation runs — so we check Content-Length before touching the body.
_MAX_REQUEST_BYTES = get_settings().max_request_bytes


@app.middleware("http")
async def limit_request_body(request: Request, call_next):
    content_length = request.headers.get("content-length")
    if content_length and content_length.isdigit() and int(content_length) > _MAX_REQUEST_BYTES:
        return JSONResponse(status_code=413, content={"detail": "request body too large"})
    return await call_next(request)


# Local-only CORS: lets a frontend dev server (e.g. React/Next.js on localhost) call
# this API. This is a backend configuration concern, not frontend code. Adjust the
# origins list for your setup, or restrict it further before exposing this beyond
# your own machine.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)
''')

CONFIG_PY = Template('''\
from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    model_id: str = $model_id
    device: str = "auto"  # "auto" | "cpu" | "cuda" | "mps"
    max_batch_size: int = $max_batch_size
    max_request_bytes: int = $max_request_bytes  # reject bodies larger than this (413)
$extra_settings
    port: int = $port


@lru_cache
def get_settings() -> Settings:
    return Settings()
''')

TEST_HEALTH_PY = '''\
from fastapi.testclient import TestClient

from app.main import app


def test_liveness():
    with TestClient(app) as client:
        resp = client.get("/health/live")
        assert resp.status_code == 200
        assert resp.json()["status"] == "ok"


def test_readiness():
    with TestClient(app) as client:
        resp = client.get("/health/ready")
        assert resp.status_code == 200
        assert resp.json()["status"] == "ready"
'''

ENV_EXAMPLE = Template('''\
MODEL_ID=$model_id
DEVICE=auto
MAX_BATCH_SIZE=$max_batch_size
MAX_REQUEST_BYTES=$max_request_bytes
PORT=$port
''')

GITIGNORE = """\
.venv/
__pycache__/
*.pyc
.env
.pytest_cache/
"""

README = Template('''\
# $title

A local FastAPI service wrapping the Hugging Face model `$model_id`
(task family: `$task`). Generated by the `hf-model-to-api` skill — local serving only,
no Docker, no cloud deployment, no frontend code.

## Run it

```bash
python -m venv .venv
source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
uvicorn app.main:app --reload --port $port
```

Then open http://127.0.0.1:$port/docs for interactive API docs.

## Endpoints

- `GET /health/live` — process is alive (no dependency checks; used for restart decisions)
- `GET /health/ready` — model is loaded and ready to serve (used to gate traffic)
- `GET /v1/info` — reports the model id currently being served
$endpoint_doc

## Calling it from a frontend

CORS is enabled for `http://localhost:3000` (typical React/Next.js dev server) in
`app/main.py`. This project only exposes the API — no frontend/client code is included
or maintained here.

## Security scope — read before exposing this anywhere

This service is built for **local, single-user use**. It has:

- **No authentication and no authorization** — anyone who can reach the port can call it.
- **No rate limiting** — a caller can send requests as fast as the hardware allows.
- **Input caps only**: batch size, per-string length, generation parameters, and a
  request-body size limit (`MAX_REQUEST_BYTES`, returns `413`). These bound cost per
  request; they are not a substitute for auth or rate limiting.

Do **not** bind it to `0.0.0.0` or expose it beyond `localhost` without first adding
authentication, rate limiting, and a hardened CORS policy. Those are out of scope for
this generated project.

## Testing

```bash
pytest
```

## Evaluation and benchmarking

Two standalone scripts from the `hf-model-to-api` skill (not part of this app) can be
copied in to test the *running* server:

- `evaluate.py` — correctness against a labeled dataset
- `benchmark.py` — latency/throughput under load

See the skill's `references/testing-and-evaluation.md` for usage.
''')

INIT_PY = "\n"


# ---------------------------------------------------------------------------
# Task-specific content
# ---------------------------------------------------------------------------

def text_classification_files(args, id2label: dict | None) -> dict[str, str]:
    if id2label:
        # JSON object keys are always strings; normalize to int at load time so
        # lookups by predicted class index (an int) actually hit.
        override_literal = json.dumps(id2label, indent=8)
        override_comment = ""
    else:
        override_literal = "None"
        override_comment = "  # TODO: verify model.config.id2label matches the real label set (see references/text-classification.md)"

    model_py = f'''\
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Optional override: only set if --id2label-json was passed to the scaffolder.
# JSON object keys are always strings, so they're normalized to int below.
_ID2LABEL_OVERRIDE = {override_literal}


class ModelBundle:
    def __init__(self, tokenizer, model, device: str, id2label: dict):
        self.tokenizer = tokenizer
        self.model = model
        self.device = device
        self.id2label = id2label


def _resolve_device(device_setting: str) -> str:
    if device_setting != "auto":
        return device_setting
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def load_model(settings) -> ModelBundle:
    device = _resolve_device(settings.device)
    tokenizer = AutoTokenizer.from_pretrained(settings.model_id)
    model = AutoModelForSequenceClassification.from_pretrained(settings.model_id)
    model.to(device)
    model.eval()
    if _ID2LABEL_OVERRIDE is not None:
        id2label = {{int(k): v for k, v in _ID2LABEL_OVERRIDE.items()}}
    else:
        id2label = model.config.id2label{override_comment}
    return ModelBundle(tokenizer, model, device, id2label)


def warm_up(bundle: ModelBundle) -> None:
    predict(bundle, ["warm-up"])


def predict(bundle: ModelBundle, texts: list[str]) -> list[dict]:
    inputs = bundle.tokenizer(
        texts, padding=True, truncation=True, max_length={args.max_input_length}, return_tensors="pt"
    ).to(bundle.device)
    with torch.no_grad():
        logits = bundle.model(**inputs).logits
        probs = torch.softmax(logits, dim=-1)
        confidences, predicted_ids = probs.max(dim=-1)
    return [
        {{"label": str(bundle.id2label[int(pid)]), "confidence": float(conf)}}
        for pid, conf in zip(predicted_ids.tolist(), confidences.tolist())
    ]
'''

    schemas_py = f'''\
from typing import Annotated

from pydantic import BaseModel, Field, StringConstraints

# Per-item length cap: bounds both memory and tokenizer work for each string, and
# returns a clean 422 instead of silently truncating. The whole-body size limit lives
# in app/main.py; these two together bound request cost.
BoundedText = Annotated[str, StringConstraints(min_length=1, max_length={args.max_chars_per_text})]


class ClassifyIn(BaseModel):
    texts: list[BoundedText] = Field(..., min_length=1, max_length={args.max_batch_size})


class ClassificationResult(BaseModel):
    label: str
    confidence: float = Field(ge=0, le=1)


class ClassifyOut(BaseModel):
    results: list[ClassificationResult]
    model_id: str
'''

    routes_py = '''\
from anyio import to_thread
from fastapi import APIRouter, HTTPException, Request

from app.core.config import get_settings
from app.core.model import predict
from app.schemas import ClassificationResult, ClassifyIn, ClassifyOut

router = APIRouter()


@router.get("/health/live")
def live():
    return {"status": "ok"}


@router.get("/health/ready")
def ready(request: Request):
    if not getattr(request.app.state, "model_ready", False):
        raise HTTPException(status_code=503, detail="model not loaded")
    return {"status": "ready"}


@router.get("/v1/info")
def info():
    return {"model_id": get_settings().model_id}


@router.post("/v1/classify", response_model=ClassifyOut)
async def classify(payload: ClassifyIn, request: Request):
    bundle = request.app.state.model_bundle
    try:
        raw_results = await to_thread.run_sync(predict, bundle, payload.texts)
    except Exception as exc:  # model/runtime failure -> typed 500, never a bare traceback
        raise HTTPException(status_code=500, detail="inference failed") from exc
    return ClassifyOut(
        results=[ClassificationResult(**r) for r in raw_results],
        model_id=get_settings().model_id,
    )
'''

    test_inference_py = '''\
from fastapi.testclient import TestClient

from app.main import app


def test_classify_happy_path():
    with TestClient(app) as client:
        resp = client.post("/v1/classify", json={"texts": ["I love this product!"]})
        assert resp.status_code == 200
        body = resp.json()
        assert len(body["results"]) == 1
        assert 0.0 <= body["results"][0]["confidence"] <= 1.0
        assert body["model_id"]


def test_classify_rejects_empty_batch():
    with TestClient(app) as client:
        resp = client.post("/v1/classify", json={"texts": []})
        assert resp.status_code == 422


def test_classify_rejects_oversized_text():
    with TestClient(app) as client:
        resp = client.post("/v1/classify", json={"texts": ["x" * 100000]})
        assert resp.status_code == 422
'''

    requirements = "\n".join([
        "fastapi>=0.110",
        "uvicorn[standard]>=0.29",
        "pydantic-settings>=2.2",
        "transformers>=4.40",
        "torch>=2.2",
        "anyio>=4.3",
        "pytest>=8.0",
        "httpx>=0.27",
    ]) + "\n"

    endpoint_doc = "- `POST /v1/classify` — body `{\"texts\": [\"...\"]}`, returns per-text label + confidence + `model_id`"

    return {
        "app/core/model.py": model_py,
        "app/schemas.py": schemas_py,
        "app/api/routes.py": routes_py,
        "tests/test_inference.py": test_inference_py,
        "requirements.txt": requirements,
        "__endpoint_doc__": endpoint_doc,
    }


def token_classification_files(args, id2label: dict | None) -> dict[str, str]:
    model_py = '''\
import torch
from transformers import pipeline


class ModelBundle:
    def __init__(self, ner_pipeline):
        self.pipeline = ner_pipeline


def _resolve_device(device_setting: str):
    # transformers pipelines take device as int (-1 = cpu, 0+ = cuda index) or "mps"
    if device_setting == "cpu":
        return -1
    if device_setting == "cuda":
        return 0
    if device_setting == "mps":
        return "mps"
    if torch.cuda.is_available():
        return 0
    return -1


def load_model(settings) -> ModelBundle:
    device = _resolve_device(settings.device)
    ner_pipeline = pipeline(
        "token-classification",
        model=settings.model_id,
        aggregation_strategy="simple",  # merges B-/I- tags into whole entities
        device=device,
    )
    return ModelBundle(ner_pipeline)


def warm_up(bundle: ModelBundle) -> None:
    extract_entities(bundle, ["Warm-up sentence."])


def extract_entities(bundle: ModelBundle, texts: list[str]) -> list[list[dict]]:
    results = []
    for text in texts:
        entities = bundle.pipeline(text)
        results.append(
            [
                {
                    "text": e["word"],
                    "label": e["entity_group"],
                    "start": int(e["start"]),
                    "end": int(e["end"]),
                    "confidence": float(e["score"]),
                }
                for e in entities
            ]
        )
    return results
'''

    schemas_py = f'''\
from typing import Annotated

from pydantic import BaseModel, Field, StringConstraints

# Per-item length cap: bounds memory and tokenizer work per string, and returns a clean
# 422 instead of silently truncating. The whole-body size limit lives in app/main.py.
BoundedText = Annotated[str, StringConstraints(min_length=1, max_length={args.max_chars_per_text})]


class NerIn(BaseModel):
    texts: list[BoundedText] = Field(..., min_length=1, max_length={args.max_batch_size})


class Entity(BaseModel):
    text: str
    label: str
    start: int
    end: int
    confidence: float = Field(ge=0, le=1)


class NerOut(BaseModel):
    results: list[list[Entity]]
    model_id: str
'''

    routes_py = '''\
from anyio import to_thread
from fastapi import APIRouter, HTTPException, Request

from app.core.config import get_settings
from app.core.model import extract_entities
from app.schemas import Entity, NerIn, NerOut

router = APIRouter()


@router.get("/health/live")
def live():
    return {"status": "ok"}


@router.get("/health/ready")
def ready(request: Request):
    if not getattr(request.app.state, "model_ready", False):
        raise HTTPException(status_code=503, detail="model not loaded")
    return {"status": "ready"}


@router.get("/v1/info")
def info():
    return {"model_id": get_settings().model_id}


@router.post("/v1/extract-entities", response_model=NerOut)
async def extract(payload: NerIn, request: Request):
    bundle = request.app.state.model_bundle
    try:
        raw_results = await to_thread.run_sync(extract_entities, bundle, payload.texts)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="inference failed") from exc
    return NerOut(
        results=[[Entity(**e) for e in per_text] for per_text in raw_results],
        model_id=get_settings().model_id,
    )
'''

    test_inference_py = '''\
from fastapi.testclient import TestClient

from app.main import app


def test_extract_entities_happy_path():
    with TestClient(app) as client:
        resp = client.post(
            "/v1/extract-entities", json={"texts": ["Barack Obama was born in Hawaii."]}
        )
        assert resp.status_code == 200
        body = resp.json()
        assert len(body["results"]) == 1
        assert body["model_id"]


def test_extract_entities_rejects_empty_batch():
    with TestClient(app) as client:
        resp = client.post("/v1/extract-entities", json={"texts": []})
        assert resp.status_code == 422


def test_extract_entities_rejects_oversized_text():
    with TestClient(app) as client:
        resp = client.post("/v1/extract-entities", json={"texts": ["x" * 100000]})
        assert resp.status_code == 422
'''

    requirements = "\n".join([
        "fastapi>=0.110",
        "uvicorn[standard]>=0.29",
        "pydantic-settings>=2.2",
        "transformers>=4.40",
        "torch>=2.2",
        "anyio>=4.3",
        "pytest>=8.0",
        "httpx>=0.27",
    ]) + "\n"

    endpoint_doc = "- `POST /v1/extract-entities` — body `{\"texts\": [\"...\"]}`, returns entities (text, label, span, confidence) per input text + `model_id`"

    return {
        "app/core/model.py": model_py,
        "app/schemas.py": schemas_py,
        "app/api/routes.py": routes_py,
        "tests/test_inference.py": test_inference_py,
        "requirements.txt": requirements,
        "__endpoint_doc__": endpoint_doc,
    }


def embeddings_files(args, id2label: dict | None) -> dict[str, str]:
    model_py = '''\
import torch
from sentence_transformers import SentenceTransformer


class ModelBundle:
    def __init__(self, model, device: str):
        self.model = model
        self.device = device


def _resolve_device(device_setting: str) -> str:
    if device_setting != "auto":
        return device_setting
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def load_model(settings) -> ModelBundle:
    device = _resolve_device(settings.device)
    model = SentenceTransformer(settings.model_id, device=device)
    return ModelBundle(model, device)


def warm_up(bundle: ModelBundle) -> None:
    embed(bundle, ["warm-up"])


def embed(bundle: ModelBundle, texts: list[str]) -> list[list[float]]:
    vectors = bundle.model.encode(
        texts, convert_to_numpy=True, normalize_embeddings=True, batch_size=len(texts)
    )
    return vectors.tolist()
'''

    schemas_py = f'''\
from typing import Annotated

from pydantic import BaseModel, Field, StringConstraints

# Per-item length cap: bounds memory and encoding work per string, and returns a clean
# 422 instead of silently truncating. The whole-body size limit lives in app/main.py.
BoundedText = Annotated[str, StringConstraints(min_length=1, max_length={args.max_chars_per_text})]


class EmbedIn(BaseModel):
    texts: list[BoundedText] = Field(..., min_length=1, max_length={args.max_batch_size})


class EmbedOut(BaseModel):
    embeddings: list[list[float]]
    dimensions: int
    model_id: str
'''

    routes_py = '''\
from anyio import to_thread
from fastapi import APIRouter, HTTPException, Request

from app.core.config import get_settings
from app.core.model import embed
from app.schemas import EmbedIn, EmbedOut

router = APIRouter()


@router.get("/health/live")
def live():
    return {"status": "ok"}


@router.get("/health/ready")
def ready(request: Request):
    if not getattr(request.app.state, "model_ready", False):
        raise HTTPException(status_code=503, detail="model not loaded")
    return {"status": "ready"}


@router.get("/v1/info")
def info():
    return {"model_id": get_settings().model_id}


@router.post("/v1/embed", response_model=EmbedOut)
async def create_embeddings(payload: EmbedIn, request: Request):
    bundle = request.app.state.model_bundle
    try:
        vectors = await to_thread.run_sync(embed, bundle, payload.texts)
    except Exception as exc:
        raise HTTPException(status_code=500, detail="inference failed") from exc
    dims = len(vectors[0]) if vectors else 0
    return EmbedOut(embeddings=vectors, dimensions=dims, model_id=get_settings().model_id)
'''

    test_inference_py = '''\
from fastapi.testclient import TestClient

from app.main import app


def test_embed_happy_path():
    with TestClient(app) as client:
        resp = client.post("/v1/embed", json={"texts": ["hello world"]})
        assert resp.status_code == 200
        body = resp.json()
        assert len(body["embeddings"]) == 1
        assert body["dimensions"] == len(body["embeddings"][0])
        assert body["model_id"]


def test_embed_rejects_empty_batch():
    with TestClient(app) as client:
        resp = client.post("/v1/embed", json={"texts": []})
        assert resp.status_code == 422


def test_embed_rejects_oversized_text():
    with TestClient(app) as client:
        resp = client.post("/v1/embed", json={"texts": ["x" * 100000]})
        assert resp.status_code == 422
'''

    requirements = "\n".join([
        "fastapi>=0.110",
        "uvicorn[standard]>=0.29",
        "pydantic-settings>=2.2",
        "sentence-transformers>=2.7",
        "torch>=2.2",
        "anyio>=4.3",
        "pytest>=8.0",
        "httpx>=0.27",
    ]) + "\n"

    endpoint_doc = "- `POST /v1/embed` — body `{\"texts\": [\"...\"]}`, returns L2-normalized embedding vectors + `dimensions` + `model_id`. Vectors from different model versions are NOT comparable — see references/embeddings.md."

    return {
        "app/core/model.py": model_py,
        "app/schemas.py": schemas_py,
        "app/api/routes.py": routes_py,
        "tests/test_inference.py": test_inference_py,
        "requirements.txt": requirements,
        "__endpoint_doc__": endpoint_doc,
    }


def image_generation_files(args, id2label: dict | None) -> dict[str, str]:
    model_py = '''\
import torch
from diffusers import DiffusionPipeline


class ModelBundle:
    def __init__(self, pipe, device: str):
        self.pipe = pipe
        self.device = device


def _resolve_device(device_setting: str) -> str:
    if device_setting != "auto":
        return device_setting
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def load_model(settings) -> ModelBundle:
    device = _resolve_device(settings.device)
    dtype = torch.float16 if device == "cuda" else torch.float32
    pipe = DiffusionPipeline.from_pretrained(settings.model_id, torch_dtype=dtype)
    pipe = pipe.to(device)
    return ModelBundle(pipe, device)


def warm_up(bundle: ModelBundle) -> None:
    # Tiny, cheap warm-up: 1 step at low resolution just to trigger CUDA kernel
    # compilation / graph warm-up, not to produce a usable image.
    generate(bundle, "warm-up", num_inference_steps=1, width=64, height=64)


def generate(bundle: ModelBundle, prompt: str, num_inference_steps: int, width: int, height: int):
    result = bundle.pipe(
        prompt,
        num_inference_steps=num_inference_steps,
        width=width,
        height=height,
    )
    return result.images[0]
'''

    schemas_py = '''\
from pydantic import BaseModel, Field


class GenerateIn(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=1000)
    num_inference_steps: int = Field(default=25, ge=1, le=100)
    width: int = Field(default=512, ge=64, le=1024)
    height: int = Field(default=512, ge=64, le=1024)


class GenerateOut(BaseModel):
    image_base64: str
    format: str = "png"
    model_id: str
'''

    routes_py = '''\
import base64
import io

from anyio import to_thread
from fastapi import APIRouter, HTTPException, Request

from app.core.config import get_settings
from app.core.model import generate
from app.schemas import GenerateIn, GenerateOut

router = APIRouter()


@router.get("/health/live")
def live():
    return {"status": "ok"}


@router.get("/health/ready")
def ready(request: Request):
    if not getattr(request.app.state, "model_ready", False):
        raise HTTPException(status_code=503, detail="model not loaded")
    return {"status": "ready"}


@router.get("/v1/info")
def info():
    return {"model_id": get_settings().model_id}


@router.post("/v1/generate", response_model=GenerateOut)
async def generate_image(payload: GenerateIn, request: Request):
    bundle = request.app.state.model_bundle
    try:
        image = await to_thread.run_sync(
            generate,
            bundle,
            payload.prompt,
            payload.num_inference_steps,
            payload.width,
            payload.height,
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail="generation failed") from exc
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    return GenerateOut(image_base64=encoded, model_id=get_settings().model_id)
'''

    test_inference_py = '''\
from fastapi.testclient import TestClient

from app.main import app


def test_generate_rejects_empty_prompt():
    with TestClient(app) as client:
        resp = client.post("/v1/generate", json={"prompt": ""})
        assert resp.status_code == 422


def test_generate_rejects_oversized_dimensions():
    with TestClient(app) as client:
        resp = client.post("/v1/generate", json={"prompt": "a cat", "width": 4096, "height": 4096})
        assert resp.status_code == 422

# Note: a happy-path generation test is deliberately not included here by default —
# running a real diffusion model in CI/test is slow and often needs a GPU. Add one
# manually (marked @pytest.mark.slow or similar) once the project is running locally.
'''

    requirements = "\n".join([
        "fastapi>=0.110",
        "uvicorn[standard]>=0.29",
        "pydantic-settings>=2.2",
        "diffusers>=0.27",
        "transformers>=4.40",
        "torch>=2.2",
        "accelerate>=0.29",
        "anyio>=4.3",
        "pytest>=8.0",
        "httpx>=0.27",
    ]) + "\n"

    endpoint_doc = (
        "- `POST /v1/generate` — body `{\"prompt\": \"...\", \"num_inference_steps\": 25, "
        "\"width\": 512, \"height\": 512}`, returns a base64-encoded PNG + `model_id`. "
        "Single-prompt-per-request by design (see references/image-generation.md — batching "
        "trades latency for throughput and rarely helps a local single-user setup)."
    )

    return {
        "app/core/model.py": model_py,
        "app/schemas.py": schemas_py,
        "app/api/routes.py": routes_py,
        "tests/test_inference.py": test_inference_py,
        "requirements.txt": requirements,
        "__endpoint_doc__": endpoint_doc,
    }


TASK_BUILDERS = {
    "text-classification": text_classification_files,
    "token-classification": token_classification_files,
    "embeddings": embeddings_files,
    "image-generation": image_generation_files,
}


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def build_extra_settings(task: str, args) -> str:
    if task in ("text-classification", "token-classification"):
        return f"    max_input_length: int = {args.max_input_length}\n"
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model-id", required=True)
    parser.add_argument("--task", required=True, choices=TASK_CHOICES)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--id2label-json", default=None, help="JSON string or path to a JSON file mapping label id -> label name (classification/NER only)")
    parser.add_argument("--max-batch-size", type=int, default=8)
    parser.add_argument("--max-input-length", type=int, default=512, help="Max token length for text tasks")
    parser.add_argument("--max-chars-per-text", type=int, default=10000, help="Max characters per input string (text tasks); over this returns 422")
    parser.add_argument("--max-request-mb", type=float, default=10.0, help="Max request body size in MB; over this returns 413")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--title", default=None)
    args = parser.parse_args()

    max_request_bytes = int(args.max_request_mb * 1024 * 1024)

    out_dir = Path(args.output_dir)
    if out_dir.exists() and any(out_dir.iterdir()):
        print(f"Refusing to scaffold into non-empty directory: {out_dir}", file=sys.stderr)
        return 1

    title = args.title or f"{args.model_id} API"

    id2label = None
    if args.id2label_json:
        raw = args.id2label_json
        path = Path(raw)
        text = path.read_text() if path.is_file() else raw
        try:
            id2label = json.loads(text)
        except json.JSONDecodeError:
            print("Could not parse --id2label-json as JSON or a path to a JSON file.", file=sys.stderr)
            return 1

    builder = TASK_BUILDERS[args.task]
    task_files = builder(args, id2label)
    endpoint_doc = task_files.pop("__endpoint_doc__")

    files: dict[str, str] = {
        "app/__init__.py": INIT_PY,
        "app/core/__init__.py": INIT_PY,
        "app/api/__init__.py": INIT_PY,
        # title/model_id are embedded into generated Python source, so they must be
        # inserted as escaped literals (json.dumps) — never raw inside quotes, or a value
        # containing a quote/newline could break out and inject code into the module.
        "app/main.py": MAIN_PY.substitute(title=json.dumps(title)),
        "app/core/config.py": CONFIG_PY.substitute(
            model_id=json.dumps(args.model_id),
            max_batch_size=args.max_batch_size,
            max_request_bytes=max_request_bytes,
            extra_settings=build_extra_settings(args.task, args),
            port=args.port,
        ),
        "tests/test_health.py": TEST_HEALTH_PY,
        ".env.example": ENV_EXAMPLE.substitute(
            model_id=args.model_id,
            max_batch_size=args.max_batch_size,
            max_request_bytes=max_request_bytes,
            port=args.port,
        ),
        ".gitignore": GITIGNORE,
        "README.md": README.substitute(
            title=title,
            model_id=args.model_id,
            task=args.task,
            port=args.port,
            endpoint_doc=endpoint_doc,
        ),
        **task_files,
    }

    for rel_path, content in files.items():
        full_path = out_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")

    print(f"Scaffolded {len(files)} files into {out_dir}")
    for rel_path in sorted(files):
        print(f"  {rel_path}")

    todos = [f for f, content in files.items() if "TODO" in content]
    if todos:
        print("\nFiles with TODO markers to review before running:")
        for t in todos:
            print(f"  {t}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
